[theme]
base = "light"
primaryColor = "#1B1B1E"
backgroundColor = "#F1F1EE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17171A"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
