[theme]
base = "light"
primaryColor = "#2F6BFF"
backgroundColor = "#EEF3FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14182B"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
